module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: ['**/*.(t|j)s'],
  coveragePathIgnorePatterns: [
    'dist',
    'build-migration',
    'node_modules',
    '.eslintrc.js',
    '.prettierrc.js',
    'jest.config.ts',
    'src/config',
    'src/factories',
    'database/seeders',
    '.*/constants',
    '.*/main.ts',
    '.*/filter',
    '.*/coverage/lcov-report',
    '.*/migrations',
    '.*/repositories',
    '.stub.ts',
    '.spec.ts',
    '.module.ts',
    'constant.ts',
  ],
  coverageDirectory: 'coverage',
  testEnvironment: 'node',
  moduleNameMapper: {
    '^src/(.*)': '<rootDir>/src/$1',
    '^test/(.*)': '<rootDir>/test/$1',
  },
  setupFiles: ['dotenv/config', '<rootDir>/test/set-env-vars.ts'],
  setupFilesAfterEnv: [
    './test/mocks/autobahn-secret-manager.mock.ts',
    './test/mocks/fs.mock.ts',
    './test/mocks/aws-s3.mock.ts',
  ],
};
